name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - uses: actions/checkout@v4

      - name: install deps
        run: npm install

      - name: Build vite app
        run: npm run build
